name: Bug Report
description: Report a bug
title: "[Bug]: "
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: Clear description of the bug
    validations:
      required: true
      
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. See error
    validations:
      required: true
      
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
    validations:
      required: true
      
  - type: textarea
    id: environment
    attributes:
      label: Environment
      placeholder: |
        - OS: [e.g., macOS]
        - Browser: [e.g., Chrome]
        - Node: [e.g., 22.0.0]
    validations:
      required: true
